### ISSUE TITLE
LD-score estimated heritabilities are not robust.

### ISSUE THREAD

**Issue by babak-ra** [bvilhjal/ldpred#72] opened 2019-03-27 03:06 UTC
LDpred uses `h2` computed using LD-score regression's method for inference, and it has an important role. I have been playing with different values of `--N` for a CAD meta-analysis and the `h2` I get varies significantly:

```
LD-score estimated genome-wide heritability: 0.0382  # N:  184304 (the correct sample size)
LD-score estimated genome-wide heritability: 0.0752  # N:  210000
LD-score estimated genome-wide heritability: 0.0929  # N:  225000
LD-score estimated genome-wide heritability: 0.1176  # N:  250000
LD-score estimated genome-wide heritability: 0.2290  # N:  500000
LD-score estimated genome-wide heritability: 0.2661  # N:  750000
LD-score estimated genome-wide heritability: 0.2846  # N: 1000000
```

Is this expected?

**Comment by babak-ra** [comment] 2019-03-28 17:28
I should add that with everything being equal (set of SNPs, ref panel, etc), LD-score regression reports the following:

```
Total Observed scale h2: 0.0682 (0.0044) # N:  184,304 (the correct sample size)
Total Observed scale h2: 0.0126 (0.0008)  # N: 1,000,000
```

**Comment by marielohcs** [comment] 2019-04-28 13:32
Actually I think I might have a similar problem (reported the issue in another thread).
I ran 2 similar analysis and the one with bigger sample size had heritability=Inf and the subsequent steps (ldpred) won't run, although the coord step was fine.

**Comment by bvilhjal** [comment] 2019-05-15 09:29
Thanks for your comments on this.  I apologize for the slow reply on this issue, but I was on holidays in April.  

In the LD score regression equation, the sample size is a parameter.  Hence, the heritability estimate is approximately linear in the sqrt(N).  However, currently when the effect estimates are derived sample sizes defined at the coordination step are used (either read in the file, or parsed), but these are then replaced with the sample size given here for the h2 estimate.  I believe it would be better not to do that, so I will leave this issue open until that's done.

**Comment by babak-ra** [comment] 2019-05-15 13:42
Thanks so much for your response. I am still not sure why LD-score regression's heritability estimate is significantly higher than LDpred's.

**Comment by bvilhjal** [comment] 2019-05-17 22:32
Hi,

It’s probably because LDpred calculates the LD scores itself and forces 1 as the intercept in the regression, etc.

Best,
Bjarni

**Comment by bvilhjal** [comment] 2019-10-17 10:24
This should be fixed now, in that it uses the sample size available in the sum stats by default now.

**Closed by bvilhjal** 2019-10-17 10:24 UTC
