### ISSUE TITLE
Could validation sites be a subset of LD refercence sites for same samples

### ISSUE THREAD

**Issue by wym0072003** [bvilhjal/ldpred#67] opened 2019-03-15 20:34 UTC
Hi Bjarni,
Could the Validation samples be the same with LD reference samples but validation genotypes is a subset of LD reference genotypes?

I got risk scores in this way and got very high predicting accuracy by dividing validation group into training and testing data sets. I am wondering if there were some bias in my risk score calculation which causes overestimated predicting results.
Thanks.

best,

Yiming

**Comment by bvilhjal** [comment] 2019-03-15 21:00
Hi, 

I am not sure I understand your setup, but unless you generated the summary stats on the data that you're validating into, I have a hard time understanding why one would get biased predictions.

I'll close this issue, as this is not a bug nor an improvement request.

Cheers,
Bjarni

**Closed by bvilhjal** 2019-03-15 21:00 UTC

**Comment by wym0072003** [comment] 2019-03-29 19:40
Thank you for your answers.

best,

Yiming
